### ISSUE TITLE
Smaller output files

### ISSUE THREAD

**Issue by kell-nl** [slackspace-io/gopro-max-video-tools#1]
The script works like a charm (after removing the 1500 frames limit), however the output is huge. A full size chunk from the GoPro (8 minutes) is 3.7GB. After converting it with this script it was 57.3GB. With the official GoPro app the resulting output is smaller than the original.

I don't need to do any editing with the resulting files. For me it's good as is, so it would be great if I can directly export to a smaller format. Can you add that as an option?

**Comment by dawonn** [comment]
Same here issue here, a year later :pray:
